````plantuml 
@startjson memoryAddress
{
    "dataSegment": [
        {
            "memoryAddress": "000F",
            "nextUser": "0022h",
            "firstGame": "0023h",
            "credentials": "01",
            "isUserActive": "01",
            "nameSize": "06",
            "nameStr": "Daniel",
            "passwordSize": "0Dh",
            "passwordStr": "3024465830102",
            "games": [
                {
                    "memoryAddress": "0023h",
                    "userAddress": "000F",
                    "nextGame": "0024h",
                    "time": "400",
                    "score": "1000",
                    "level": "1",
                    "nextGames": [
                        {
                            "memoryAddress": "0023h",
                            "userAddress": "000F",
                            "nextGame": "0024h",
                            "time": "400",
                            "score": "1000",
                            "level": "1",
                            "nextGames": [
                                {
                                    "memoryAddress": "0023h",
                                    "userAddress": "000F",
                                    "nextGame": "0024h",
                                    "time": "400",
                                    "score": "1000",
                                    "level": "1",
                                    "nextGames": []
                                }
                            ]
                        }
                    ]
                }
            ],
            "users": [
                {
                    "memoryAddress": "000F",
                    "nextUser": "0022h",
                    "firstGame": "0023h",
                    "credentials": "01",
                    "isUserActive": "01",
                    "nameSize": "06",
                    "nameStr": "Daniel",
                    "passwordSize": "0Dh",
                    "passwordStr": "3024465830102",
                    "games": [
                        {
                            "memoryAddress": "0023h",
                            "userAddress": "000F",
                            "nextGame": "0024h",
                            "time": "400",
                            "score": "1000",
                            "level": "1",
                            "nextGames": [
                                {
                                    "memoryAddress": "0023h",
                                    "userAddress": "000F",
                                    "nextGame": "0024h",
                                    "time": "400",
                                    "score": "1000",
                                    "level": "1",
                                    "nextGames": [
                                        {
                                            "memoryAddress": "0023h",
                                            "userAddress": "000F",
                                            "nextGame": "0024h",
                                            "time": "400",
                                            "score": "1000",
                                            "level": "1",
                                            "nextGames": []
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    "users": [
                        {
                            "memoryAddress": "000F",
                            "nextUser": "0022h",
                            "firstGame": "0023h",
                            "credentials": "01",
                            "isUserActive": "01",
                            "nameSize": "06",
                            "nameStr": "Daniel",
                            "passwordSize": "0Dh",
                            "passwordStr": "3024465830102",
                            "games": [
                                {
                                    "memoryAddress": "0023h",
                                    "userAddress": "000F",
                                    "nextGame": "0024h",
                                    "time": "400",
                                    "score": "1000",
                                    "level": "1",
                                    "nextGames": [
                                        {
                                            "memoryAddress": "0023h",
                                            "userAddress": "000F",
                                            "nextGame": "0024h",
                                            "time": "400",
                                            "score": "1000",
                                            "level": "1",
                                            "nextGames": [
                                                {
                                                    "memoryAddress": "0023h",
                                                    "userAddress": "000F",
                                                    "nextGame": "0024h",
                                                    "time": "400",
                                                    "score": "1000",
                                                    "level": "1",
                                                    "nextGames": [
                                                      
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            "users": []
                        }
                    ]
                }
            ]
        }
    ]
}
@endjson
```